Fix mypy errors in test_bitvector.py
This is a fairly straightforward process for the most part, as most of the
errors are caused by either:

* Assertion functions not being type signatures
* Test cases with ill typed inputs not being annotated with `#type: ignore`

One tricky corner case is this test case:

```py
        self.assertUnOpExpected(
            lambda b: b & (2 ** b.size() - 1),
            lambda b: b)
```

Surprisingly, `mypy` complains about the `2 ** b.size()` part:

```
cryptol/test/test_bitvector.py:148: error: Returning Any from function declared to return "BV"
```

I'm surprised that `mypy` couldn't figure this one out, but nevertheless, I
worked around this by using `cast(int, 2 ** b.size() - 1)`.

Fixes #149.